services:
  postgres:
    container_name: "postgres-evo"
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      server:
        ipv4_address: 172.50.0.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres_data:
    name: postgres_data

networks:
  server:
    external: true
